# Model Configuration
model:
  model_name: 'google-bert/bert-base-uncased' # Hugging Face model
  model_max_length: 512
  freeze_bert: false
  classifier_lr: 1e-3
  classifier_dropout: 0.1
  no_crf: false
  pooler: 'last'
  prev_path: null # Pretrained Model Path: Use None if no pretrained model is being used
  cache_dir: null

# Dataset Configuration
dataset:
  train_file: 'train.jsonl'
  validation_file: 'validation.jsonl'
  test_file: 'test.jsonl'
  format: 'iob2' # format: ["iob1", "iob2", "ioe1", "ioe2", "iobes", "bilou"]
  pretokenize: true


# Dataloader
remove_unused_columns: false

# Training Parameters
num_train_epochs: 4
per_device_train_batch_size: 10
per_device_eval_batch_size: 20
lr_scheduler_type: "linear"
warmup_ratio: 0.06

# Optimizer
optim: "adamw_torch"
adam_beta1: 0.9
adam_beta2: 0.98
adam_epsilon: 1.e-6

# Learning Rate and weight decay Configuration
learning_rate: 1.e-5
weight_decay: 0.01
max_grad_norm: 0.0

# logging
log_level: 'info'
logging_strategy: 'epoch'
logging_steps: 10
report_to: 'wandb'

# Save
save_strategy: 'epoch'
save_total_limit: 3 #maximum amount of checkpoints to save

# Evaluation
eval_strategy: 'epoch'
metric_for_best_model: 'f1'
load_best_model_at_end: true
eval_on_start: false
